title: LUFT-AQUILA
description: A sky sailing Electron.
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/profile/og.png
      
locale: ko_KR

permalink: /blog/:categories/:title/
url: "https://luftaquila.io"
future: true

include:
  - _pages
  - _works
  - _docs
  - _photos

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

collections:
  works:
    output: true
    permalink: /works/:path/
    
  docs:
    output: true
    permalink: /docs/:path/
    
  photos:
    output: true
    permalink: /photos/:path/
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-target-blank

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
